# Generated by Django 5.1.4 on 2025-01-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
