# Generated by Django 5.1.5 on 2025-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_landlord',
            name='interaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('view', 'View')], default='view', max_length=10),
        ),
        migrations.AddField(
            model_name='post_tenant',
            name='interaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('view', 'View')], default='view', max_length=10),
        ),
        migrations.AddField(
            model_name='post_tenant',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
