# Generated by Django 5.1.5 on 2025-02-01 18:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0004_post_landlord_interaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemotel',
            name='url',
        ),
        migrations.AddField(
            model_name='imagemotel',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/demo/image/upload/sample.jpg', max_length=255, verbose_name='image'),
        ),
    ]
