# Generated by Django 5.1.5 on 2025-02-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0007_remove_post_tenant_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Motel.post_landlord'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Motel.post_tenant'),
        ),
        migrations.AddField(
            model_name='post_tenant',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
