# Generated by Django 5.1.5 on 2025-02-03 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0008_remove_comment_post_comment_post_landlord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tenant',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
