# Generated by Django 5.1.5 on 2025-02-03 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0009_alter_post_tenant_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemotel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagemotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
