# Generated by Django 5.1.5 on 2025-02-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0010_imagemotel_active_imagemotel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmanagement',
            name='userAccount',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
