# Generated by Django 5.1.5 on 2025-02-03 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0011_remove_adminmanagement_useraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmanagement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminmanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminmanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
