# Generated by Django 5.1.5 on 2025-02-04 08:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0012_adminmanagement_active_adminmanagement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_landlord',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
