# Generated by Django 5.1.5 on 2025-02-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0013_post_landlord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_landlord',
            name='image',
        ),
    ]
